sudo: required

dist: trusty

before_install: 
  - if [ $TRAVIS_OS_NAME == "linux" ]; then 
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - sudo apt-get install mono-complete mono-devel
  - wget -O os.rpm http://oscript.io/downloads/night-build/onescript-engine-1.0.19-1.fc25.noarch.rpm
  - sudo apt-get install alien
  - sudo alien os.rpm
  - sudo dpkg -i *.deb; sudo apt install -f
  - sudo oscript /usr/share/oscript/lib/opm/src/opm.os install opm
  - oscript

install: 
  - sudo oscript /usr/share/oscript/lib/opm/src/opm.os install

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - oscript test.os 
